/*
 *
 * Preview constants
 *
 */

enum ActionTypes {
  SET_QUANTITY_ACTION = 'app/Preview/SET_QUANTITY_ACTION',
  SET_QUANTITY_ACTION_SUCCESS = 'app/Preview/SET_QUANTITY_ACTION_SUCCESS',
  SET_QUANTITY_ACTION_FAILED = 'app/Preview/SET_QUANTITY_ACTION_FAILED',

  GET_QUANTITY_HISTORY_ACTION = 'app/Preview/GET_QUANTITY_HISTORY_ACTION',
  GET_QUANTITY_HISTORY_SUCCESS = 'app/Preview/GET_QUANTITY_HISTORY_SUCCESS',
  GET_QUANTITY_HISTORY_FAILED = 'app/Preview/GET_QUANTITY_HISTORY_FAILED',

  SET_PRICE_ACTION = 'app/Preview/SET_PRICE_ACTION',
  SET_PRICE_ACTION_SUCCESS = 'app/Preview/SET_PRICE_ACTION_SUCCESS',
  SET_PRICE_ACTION_FAILED = 'app/Preview/SET_PRICE_ACTION_FAILED',

  GET_PRICE_HISTORY_ACTION = 'app/Preview/GET_PRICE_HISTORY_ACTION',
  GET_PRICE_HISTORY_ACTION_SUCCESS = 'app/Preview/GET_PRICE_HISTORY_ACTION_SUCCESS',
  GET_PRICE_HISTORY_ACTION_FAILED = 'app/Preview/GET_PRICE_HISTORY_ACTION_FAILED',
}

export default ActionTypes;
